apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-test
  template:
    metadata:
      labels:
        app: mlops-test
    spec:
      containers:
        - name: mlops-test
          image: ghcr.io/guntwo66/mlops-test:efa70f52497883d8182eff25998f1c58aaec3f6a
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
